admin:
  existingSecret: grafana-admin-secret
  userKey: admin
  passwordKey: strong-admin-password

service:
  type: NodePort

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
        editable: true