apiVersion: v1
kind: Pod
metadata:
  name: stress-test
  namespace: default
spec:
  containers:
    - name: stress
      image: ubuntu
      command: ["bash", "-c"]
      args:
        - apt update &&
          apt install -y stress &&
          stress --cpu 2 --vm 2 --vm-bytes 1024M --timeout 300s
      resources:
        limits:
          memory: "2Gi"
          cpu: "1000m"
  restartPolicy: Never
