{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-chart.fullname" . }}-config
  labels:
    {{- include "flask-chart.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config.data }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}